---

# task file for hadenlabs.monit

- name: Install monit package dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  register: install_monit_package_dependencies
  when:
    - _monit_package_dependencies is defined
  with_items:
    - _{{ _monit_package_dependencies | default([]) }}
  tags:
    - packages
    - dependencies
