---
# task for hadenlabs.monit

- name: Create configs
  template: src=etc/monit/conf.d/{{ item.type | default('base') }}.conf.j2
            dest=/etc/monit/conf.d/{{ item.type | default('base') }}_{{ item.process | default(item.pid | basename | replace('.pid', '')) }}.conf
            owner=root group=root mode=0644
  with_flattened:
    - "{{ monit_process_list | default([]) }}"
    - "{{ monit_process_group_list | default([]) }}"
    - "{{ monit_process_host_list | default([]) }}"
    - "{{ monit_process_dependent_list | default([]) }}"
  when:
    - item.delete is undefined and item.pid is defined
  notify: [ 'Test monit and reload' ]