---
# task for hadenlabs.monit

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0700
  with_items: "{{ _monit_templates | default([]) }}"
  when:
    - _monit_templates is defined
  notify: [ 'Test monit and reload' ]
